disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Pwnlentoni"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Pwnlentoni page"
copyright = "©2026 Pwnlentoni"
logo = "Nuovo\\ progetto\\(2\\).png "

["params.author"]
name = ""
