disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "pwnlentoni"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Pwnlentoni page"
copyright = "©2026 Pwnlentoni"
logo = "img/logo.svg"
secondaryLogo = "img/logo-light.svg"

["params.author"]
name = ""
