# -- Main Menu --
[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "Writeups"
  pageRef = "writeups"
  weight = 20

#[[main]]
#  name = "Sponsors"
#  pageRef = "sponsors"
#  weight = 30

