# The URL the site will be built for
base_url = "https://pwnlentoni.team"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "anatole-zola"

default_language = "en"

taxonomies = [
  { name = "tags" }
]

[languages.en]
weight = 1
title = "pwnlentoni"
languageName = "English"
languageCode = "en"
relativeURL = false
[languages.en.translations]
language_name = "English"
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
date_format = "%Y-%m-%d"
next_page = "Next Page"
last_page = "Last Page"


[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"


[extra]
# Put all your custom variables here
default_theme = "dark"
list_pages = false
twitter_card = true



[[extra.header_nav]]
en = { name = "/home/", url = "/" }

[[extra.header_nav]]
en = { name = "/blog/", url = "/blog" }

