# The URL the site will be built for
base_url = "https://pwnlentoni.team"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "anemone"

default_language = "en"

[languages.en]
weight = 1
title = "pwnlentoni"
languageName = "English"
languageCode = "en"
relativeURL = false


[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"


[extra]
# Put all your custom variables here
default_theme = "dark"
list_pages = false
twitter_card = true



[[extra.header_nav]]
en = { name = "/home/", url = "/" }

[[extra.header_nav]]
en = { name = "/blog/", url = "/blog" }

